### ISSUE TITLE
[University of California San Francisco] Progress Tracker

### ISSUE THREAD

**Issue by kzollove** [kzollove/api-test#79]
### Data Contributing Site

University of California San Francisco

### Site Main Contact

Eddy Amorim

### ETL Representatives

Eddy Amorim

### Site Classification

Haven't started creating an OMOP data set

### Data Classification Type?

- [ ] EHR Data
- [ ] Flowsheets
- [ ] Waveform Data
- [ ] Image Data

### Site TODO:
- [ ] Join the GitHub Discussion
<SUB_ISSUES>
https://github.com/bridge2ai/StandardsModule/issues/16
https://github.com/bridge2ai/StandardsModule/issues/15
- [ ] Has Data Quality Dashboard (DQD) been run on your OMOP instance?
- [ ] Have the Data Quality Dashboard (DQD) results been submitted?
- [ ] Has Achilles been run on your OMOP instance?
- [ ] Have the Achilles results been submitted?
- [ ] Has flowsheet data been identified?
- [ ] Has flowsheet format been identified?
- [ ] Has site begun mapping process?
- [ ] Has Standards Module reviewed flowsheet mappings?
